apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- was.yaml
resources:
- was.yaml
images:
- name: cicd-image
  newName: grovince/rapa-cicdlab3
  newTag: v13
namespace: default
