apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- was.yaml
resources:
- was.yaml
images:
- name: cicd-image
  newName: public.ecr.aws/p7g3y4o1/rapa-devops
  newTag: v58
namespace: default
