# name: CICD

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - run: ls -al

#       - name: Set env
#         run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

#       - name: install jdk
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '11'
#           cache: 'gradle'

#       - name: chmod gradle
#         run: chmod +x ./gradlew

#       - name: build
#         run: ./gradlew build --no-daemon

#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to Amazon ECR Public
#         id: login-ecr-public
#         uses: aws-actions/amazon-ecr-login@v2
#         with:
#           registry-type: public
#           aws-region: us-east-1

#       - name: Build, tag, and push docker image to Amazon ECR
#         env:
#           REGISTRY: public.ecr.aws/p7g3y4o1/rapa-devops
#           REPOSITORY: rapa-devops
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           echo "REGISTRY: $REGISTRY"
#           echo "REPOSITORY: $REPOSITORY"
#           echo "IMAGE_TAG: $IMAGE_TAG"
#           cd Dockerfile  # Dockerfile이 있는 디렉토리로 이동
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG



#       - name: Update Kubernetes resources
#         run: |
#           cd yaml/was
#           kustomize edit set image cicd-image=${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab3:v${{ env.RELEASE_VERSION }}
#           cat kustomization.yml

#       - name: Commit & Push Image
#         uses: actions-js/push@master
#         with:
#           message: '[was] Update Image: ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab3:v${{ env.RELEASE_VERSION }}'
#           branch: main
#           github_token: ${{ secrets.TOKEN }}


name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ls -al

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: chmod gradle
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build --no-daemon

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          aws-region: us-east-1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: public.ecr.aws/p7g3y4o1/rapa-devops
          REPOSITORY: rapa-devops
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mv ./build/libs/*.war ./Dockerfile
          docker build -t $REGISTRY/$REPOSITORY:v${{ env.RELEASE_VERSION }} ./Dockerfile
          docker push $REGISTRY/$REPOSITORY:v${{ env.RELEASE_VERSION }}
          rm -Rf ./Dockerfile/*.war


      - name: Update Kubernetes resources
        run: |
          cd yaml/was
          kustomize edit set image cicd-image=${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab3:v${{ env.RELEASE_VERSION }}
          cat kustomization.yml

      - name: Commit & Push Image
        uses: actions-js/push@master
        with:
          message: '[was] Update Image: ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab3:v${{ env.RELEASE_VERSION }}'
          branch: main
          github_token: ${{ secrets.TOKEN }}
