name: CICD
on:
  push: 
    branches: [ main ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # ruuner 생성

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # gitconfig에 저장된 애들은 체크아웃
      - run: ls -al
      
      - name: Set env # 환경 변수 설정 
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        
      - name: install jdk # jdk 설치 - java 빌드 환경 세팅
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: chmod gradle
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build --no-daemon

      - name: Set up Docker Buildx 
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        run: |
          mv ./build/libs/*.war ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:v${{ env.RELEASE_VERSION }} ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:latest ./Dockerfile
          rm -Rf ./Dockerfile/*.war
          rm -Rf ./build 
          
      - name: docker images check
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker push
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:v${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:latest

      - name: Update Kubernetes resources
        run: |
          cd yaml/was
          kustomize edit set image cicd-image=${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:latest
          cat kustomization.yml
              
      - name: Commit & Push Image 
        uses: actions-js/push@master
        with:
          message: '[was] Update Image : ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab:latest'
          # rapa-cicdlab:v${{ env.RELEASE_VERSION }}
          branch: main
          github_token: ${{ secrets.TOKEN }}
